name: SpotDL Workflow

on:
  workflow_dispatch:

jobs:
  download-music:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
      
      - name: Install spotDL
        run: |
          pip install spotdl
      
      - name: Verify installation
        run: |
          spotdl --version
          ffmpeg -version
      
      - name: Download playlist
        run: |
          mkdir -p downloads
          cd downloads
          spotdl download https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M --limit 3
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-music
          path: downloads/
          retention-days: 1
